# Generated by Django 3.1.3 on 2020-11-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201113_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='picname',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='main',
            name='picurl',
            field=models.CharField(default='', max_length=250),
        ),
    ]
