# Generated by Django 3.1.3 on 2020-11-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201115_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='picnamefooter',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='main',
            name='picurlfooter',
            field=models.CharField(default='', max_length=250),
        ),
    ]
