# Generated by Django 3.1.3 on 2020-11-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201126_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='seo_keywords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='seo_txt',
            field=models.CharField(max_length=200),
        ),
    ]
